### ISSUE TITLE
building with mingw 8.1.0, static library is missing `dgetri`?

### ISSUE THREAD

**Issue by mattip** [xianyi/OpenBLAS#2920]
In the MacPython/openblas-libs repo we build with mingw v8.1.0 on windows. There seems to be a problem with the [test.f90](https://github.com/MacPython/openblas-libs/blob/master/test.f90#L49) compilation, it [cannot link](https://github.com/MacPython/openblas-libs/runs/1271453823?check_suite_focus=true#step:8:44), with the error that `dgetri` is not exported from the library. Indeed, if I do `objdump -x |grep dgetr` (in gitbash) I do not see it, but I do see traces of it:
```
$ objdump -x /c/opt/64/lib/libopenblas_v0.3.11-gcc_8_1_0.dll.a |grep dgetr
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 dgetrs_
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_dgetrs_
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 dgetrs
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_dgetrs
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 dgetrf_
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_dgetrf_
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 dgetrf
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_dgetrf
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrs_work
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrs_work
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrs
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrs
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetri_work
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetri_work
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetri
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetri
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrf_work
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrf_work
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrf2_work
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrf2_work
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrf2
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrf2
[  5](sec  1)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 LAPACKE_dgetrf
[  6](sec  3)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x0000000000000000 __imp_LAPACKE_dgetrf

```

This code used to work, I wonder what changed.

**Comment by mattip** [comment]
I see the [travis run](https://travis-ci.org/github/MacPython/openblas-libs/builds/736706090) on linux also errors, with [missing symbols when linking](https://travis-ci.org/github/MacPython/openblas-libs/jobs/736706095#L8636). Maybe there is a problem with the commands we use on [windows](https://github.com/MacPython/openblas-libs/blob/master/tools/build_openblas.sh#L69) and [linux](https://github.com/MacPython/openblas-libs/blob/master/travis-ci/build_steps.sh#L127). Should we update them somehow?

**Comment by mattip** [comment]
xref MacPython/openblas-libs#43

**Comment by martin-frbg** [comment]
I think isuruf just fixed that for me in #2919, seems I had left some copypaste mistakes in the lapack makefiles when i split the object lists according to data type.

**Comment by mattip** [comment]
Thanks. #2919 fixes the windows builds (including the 64-bit interface one), but  [the linux ones](https://travis-ci.org/github/MacPython/openblas-libs/builds/736983748) built using the 64-bit interface still are broken. These add `INTERFACE64=1 SYMBOLSUFFIX=64_` to the `make` arguments, perhaps some of our scripts need updating?

**Comment by mattip** [comment]
it seems like a problem in `make test` in `exports/Makefile` with the `linktest.c` compilation

**Comment by isuruf** [comment]
Please try latest commit on develop. https://github.com/xianyi/OpenBLAS/pull/2909 should fix that.

**Comment by martin-frbg** [comment]
There may be an additional problem with the gensymbol script - I fear my former self switched to calling the lapackobjs2... variables
lapack2objs... at some point (or something like that, I am just getting ready to debug this - nightmare fuel)

**Comment by isuruf** [comment]
Are we sure #2909 doesn't fix it? I had the same problem which was fixed by #2909.

**Comment by martin-frbg** [comment]
Unfortunately yes - I had already begun building a new Windows binary with your fixes last night and that was definitely still missing symbols compared to 0.3.10. (Actually I think now my misgivings were correct - and your #2919 _probably_ does not clear up the "lapack2" naming confusion completely - also the lapack_deprecated_objs get dropped after the initial enumeration. Testing a fix but do not want to rush it again)

**Comment by mattip** [comment]
I didn't mean to pressure you. It is fine if it takes a few days to get right. This was a big release.

**Comment by isuruf** [comment]
Yes, you are right. There are missing symbols comparing develop against 0.3.10. Here's a list https://gist.github.com/isuruf/9974570e586c959447c0aca893ef4ddd
