### ISSUE TITLE
POWER8 VSX BLAS 1/2 double precision

### ISSUE THREAD

**Issue by edelsohn** [xianyi/OpenBLAS#795]
Optimize BLAS 1/2 double precision for POWER8 VSX

**Comment by wernsaar** [comment]
Hi,

I added an optimized ddot kernel.

Performance data:
POWER8 kernel: 11 Gflops ( 6 Gflops with POWER6 kernel )

Best regards
Werner

**Comment by edelsohn** [comment]
@wernsaar Anton Blanchard sent you direct email about some performance opportunities that we noticed:

He compared ATLAS, ESSL (the IBM BLAS) and OpenBLAS using 16B aligned
arguments. Testing the functions you have implemented, we see it beat
ATLAS at many tests and mostly match ESSL. Nice work!

He does see 2-3x slower performance on sgemm, strmm, cgemm and ctrmm,
possibly because of the use of lxsspx/stxssp.

**Comment by xianyi** [comment]
@edelsohn , thank you for the feedback.
I think we need some performance tips for single precision.

**Comment by edelsohn** [comment]
@xianyi Anton emailed Werner directly. It would be helpful if Werner replied to Anton and either mentioned a better mailing list for the discussions or suggested that the discussions happen somewhere on Github.

**Comment by xianyi** [comment]
I think we can use openblas-dev mailing list.
https://groups.google.com/forum/#!forum/openblas-dev

**Comment by quickwritereader** [comment]
Guys, I wanted to know if this issue is still important and know the exact reasons why it is still open. 

> I would like to start working on Power architecture as I want to learn it. That bounty could be motivation for me if team members agree (because I see it were (probably partially) done by  @wernsaar) .

**Comment by edelsohn** [comment]
Yes, it remains open. There are some remaining issues of correctness of the assembly language implementation and of performance.

**Comment by quickwritereader** [comment]
Mr @edelsohn then I gonna start with this and learn power series so that I could involve in power9 in future, too
Offtopic: is ibm going to open bounties for z14?

**Comment by edelsohn** [comment]
I want to open bounties to optimize OpenBLAS on Power9 and z14. I have been waiting for IBM to provide a method for public, open source developer access to those systems so that developers can test performance on the systems.

**Comment by martin-frbg** [comment]
Hopefully the assembly issues are fixed (primarily by Alan Modra's work in #1078, I tried to address the remaining ones from #1263), but there has been no verification (beyond hints from #1332,#1191 suggesting that the known issues on Power8 may result from errors in the common C code).

**Comment by quickwritereader** [comment]
Thanks @martin-fbg for detailed info. I will consider those issues. 

If possible could you recap for me potential c code problems (as reading issue comments I could miss important points)
 Like what issues are still there which is not depend on architecture and exists even in generic c code.?

 ( on z13 implementaion I mostly relied on openblas test and its generic c code. I also was testing manipulating test data parameteres.)

**Comment by martin-frbg** [comment]
One bug in threaded trmv is worked around for now, there may still be errors with multithreading (across all architectures) in the level3 blas unless USE_SIMPLE_THREADED_LEVEL3 is set at compile time. (Unfortunately the latest case from #1401 appears to have a hardware/firmware component to it, so may not be useful for verifying any fixes.) Do I take it that your z13 work is completed for now ?

**Comment by quickwritereader** [comment]
On z13 there is still  blas1/2 for single precision which I was reluctant to optimize as lack of hardware simd support and the memory bound nature of blas1 functions.
On z13 I should pull request for small fix as I forgot to pr last year. So yes I want to focus on power series for now
 I think I will come back to z13 for new additions and improvements in future if I start working on z14 .

**Comment by quickwritereader** [comment]
I requested access at Red Hat Lab @ FIT.  still did not get any reply, 
So now I requested access at osuosl . There's " Ibm advocate " field (in the request form).   
Mr @edelsohn, I filled your  surname in

**Comment by edelsohn** [comment]
OSUOSL is a more productive path.

**Comment by quickwritereader** [comment]
I got an email that ppcle is main concern. As I applied for Be. If  there's not any special difference can I use ppcle as it seems future

**Comment by edelsohn** [comment]
PPC64LE is the focus.  Support for PPC64BE, especially AIX, would be nice to have, but not the focus of the issue and the bounty.

**Comment by quickwritereader** [comment]
Oh then Openblas Power8 are meant for actually le support, right?

**Comment by edelsohn** [comment]
Yes. PPC64 EL Linux Power8 VSX.

**Comment by quickwritereader** [comment]
(Last week I got power pc and installed tools). 
On coming weeks I gonna try to check power8 blas1 functions for correctness (single thread).  
(As mikrokernels are implemented using inline assembly and later fixed  there is not any need to check ABI for now for Blas1)
 **I believe that current OpenBlas Blas1 tests are not good (n is small) and misleading . But some still could be tested by  running blas2 tests (for functions which is used by blas2).  As I don't know fortran I probably will implement c code tests for that purpose** ( I already implemented some when I was checking z13).   
After that I am intending to fix or tune some functions.  
(I also made recent changes on z13 kernels inspired by Alan Modra power8 patch (I removed memory clobber and not inline attribute). I'm also going to recheck z13 after implementing blas1 tests)

**Comment by martin-frbg** [comment]
Current BLAS tests are copies of (an older version of) the tests contained in the netlib reference implementation (compare lapack-netlib/BLAS/TESTING). There is also the BLAS-Tester project by xianyi, which is based on the test cases from ATLAS and compares speed and correctness against the netlib implementation. Its executables take parameters for n and a couple of other variables.

**Comment by quickwritereader** [comment]
Oh, I was not aware of BLAS-Tester. It seems complete. I will check that. Thanks

> 
> I was writing  blas1 individual tests just modifying benchmark c codes (without using unit test framework  )

**Comment by quickwritereader** [comment]
I have tested using BLAS-Tester and also I tested with my test. It passed all tests (for both single and double).
I think it is already correct.  
 And frankly performance looked good in BLAS-Tester. Should I compare it against atlas and look for further tuning opportunities?

**Comment by edelsohn** [comment]
In Issue #1078 @amodra wrote:
"For the record, it's more than just the gcc asm() statements. The assembly files are broken too, I think, using callee-saved altivec regs without saving them.
Oh, and the patch I posted wasn't correct either. Oops. The constraints were not quite right, and I should have put vs32 etc. in the asm clobbers, not plain 32 etc. In sasum_microk_power8.c fr14..fr23 were not being trashed but some altivec regs, v20, v21, v22 and v23.
In a lot of cases by using the right vsx registers we probably don't need to touch callee-saves. There are 34 vsx regs that don't need to be saved, vs0-vs13 (corresponding to fr0-fr13),and vs32-vs51 (corresponding to v0-v19)."

Have the .S files been corrected?

**Comment by quickwritereader** [comment]
I read patch and it seems Mr.Modra already fixed c files. And I think blas1 .S files were for older power archs too.  Maybe he  meant gemm .S files that Martin recently fixed.
**No, I did not check manually. I just run my blas1 tests and also  BLAS-Tester** and results were correct .  when there is problem in input and output params and clobbers It most time affects results. (but I cant say this about vector related corruptions). 
**So I will  better re-check again to be sure if everything is correct.I will inform results.**
 (I will also try to follow Mr.Modra guide and change vector registers to proper ones if I see such cases.)

**Comment by edelsohn** [comment]
The issue with the .S files is that they allocated the vector registers in the wrong order -- utilizing registers that require additional saves and restores, and possibly not saving and restoring them in the code.  Avoiding callee-saved registers when not necessary should lead to higher performance.

**Comment by quickwritereader** [comment]
Yes I got Mr.Edelsohn. I will try to re-check all currently available power8 related blas functions (for now for double) and will inform. And I also try to change vectors to proper ones   


(( What I meant that for blas1 all power8 vector codes are in .c files. And looking at Kernel binding I saw that  for power8 some blas functions implicitly link  to .S files in which vectors were not used at all( if I dont make mistake ). And after running my tests I concluded that it is already fine and nothing left for me to do. Thats why I asked if I should do anything. 
And besides those there are blas3 functions which exactly intended for power8 and use vectors and in .S files. ))

**Comment by edelsohn** [comment]
If the BLAS1 functions already are optimal with the C implementation, nothing additional is needed.

I don't fully understand your comment about some BLAS functions implemented with non-SIMD .S files. Are the assembly files used or the C files. The C files should benefit from auto-SIMDization.

**Comment by quickwritereader** [comment]
If I remember correctly Blas1 iamin, iamax, zrot and blas2 zgemv link to .S file and others link to .c file (with inline vector asm codes).  Probably, there were reason to do them without simd.
(I dont know if .S files were converted from .c file and tuned later)   
I should recheck again as I am still new to   power arch.

**Comment by quickwritereader** [comment]
Mr @edelsohn I wanted to share the work I have done. 
Blas3: I renamed vector registers and removed unnecessary save restore from blas3 copy functions. But for main routines it remains because registers are heavily used inside. But the code is ok  as its save restore area was fixed by martin.
For this issue Blas1/2 double:
 I added izamax izamin idamax idamin simd versions with c & inline assembly. 
OpenBlas benchmark shows x1.8 ~x2 speed up for idamin/idamax, ~1.4 speed up for izamax/izamin.
( implemented with xxsel and vector compare instructions)
I also added zgemv_t and zgemv_n pure c vector simd versions (just converted from z13 c simd version. It performs at least 0.8 ~1gflops better than hand written assembly code (no simd variant) for single thread).  Converted gcc code looked decent. I think I might add speedup a little if I go with inline assembly if there will be request. 
 Zrot was also missing. I added refactored version of drot for zrot as both share the same code (just n differs)..Actually, I wrote zrot  with fused multiply add instructions and was going to replace current drot with fma version,too . but later dropped it because of the comment inside drot implementation.
(there was hint that lapack has problems with precision if fma used and thats why original contributor did not use fma)

I will try to add dgemv_t simd version as recently, I saw that special simd versin for dgemv_t(transposed)  is also missing.

[My fork github.com/quickwritereader/OpenBLAS](https://github.com/quickwritereader/OpenBLAS)
Z series:
I also looked at z13 blas1/2 double . I constantly try to improve  or reimplement  some kernels there whenever I have a extra time. So I am happy that I still got access to z13 computer.


I also wanted to ask how much bounty I can get for this issue (power 8 blas1/2 double). As some codes were already implemented and fixed. 
Thanks

**Comment by edelsohn** [comment]
Hi, Abdel

No one had completed the Power8 BLAS 1/2 projects, so I am happy to reward you with the full bounties.

Thanks, David

**Comment by quickwritereader** [comment]
I have implemented dgemv_t simd version (it has pure vector code and also inline assembly with prefetch) for case OPENBLAS_TRANS=T. 
performance tests were done using OpenBlas benchmark.
For matrixes smaller <1000 it mostly performs better and if it called with warm up calls like from 40 till 1000 it mostly performs  at  ~11gflops while previous mostly  ~8glfops. For matrixes larger >1000 it also usually performs better than previous one (dgemv_t.S) under single thread but with little gap (mostly 0.8-1gflops better) (one should set OPENBLAS_LOOPS above 10 to see improvements). 
I think dgemv_t.S could be replaced with this one. (note that dgemv is memory bound.)   in future I'll try to improve it and come with better solution.

**Comment by quickwritereader** [comment]
@martin-frbg if possible could you recheck and close this issue. I would like to claim for bounty if everything is alright.
thanks

**Comment by martin-frbg** [comment]
Everything looked good from my (admittedly low) perspective when I merged your PR, thank you very much for your work on this. As far as I understand the protocol, closing of the issue and awarding the bounty would be David Edelsohn's honor ? :)

**Comment by quickwritereader** [comment]
@martin-frbg yes its better to wait for approval.
Actually, I'm still new at this and still need approval and guidance by experts. I tried my best. I believe in time I will come with better solutions.

**Comment by edelsohn** [comment]
The current patches from @quickwritereader are a clear improvement. I think this is good progress. Better performance, corrected the ABI, and made the code more robust. This is a good solution for the issue.

**Comment by quickwritereader** [comment]
Mr.Edelsohn,, thanks for the support. 
Guys, please also note that I always try to improve or fix issues if I see them in my works . @martin-frbg
